### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NishantSingh10** [PavanMudigonda/allure-html-reporter-github-pages#1]
is there any way to get percentage of allure report in github action, i want to break the pipeline if percentage is less that 75%.

**Comment by PavanMudigonda** [comment]
@NishantSingh10 

I have added this feature as your request. Please add step from below example workflow ! Preferably as your last step after gh pages deploy ! please hit star on my repo and close this issue !

https://github.com/PavanMudigonda/allure-html-reporter-github-pages/blob/main/.github/workflows/quality-gate.yml

**Comment by NishantSingh10** [comment]
Thank you so much for adding this feature, this is really helpful, Just one question, if CSV file is in external repository then How can i import that ? @PavanMudigonda

**Comment by PavanMudigondaTR** [comment]
@NishantSingh10  Since you deploy gh-pages branch from repo 1 to repo 2. you will still have csv repo 1 workflow after gh-pages deploy step. if you do "ls - R" you will see it under allure-results/data folder. so if you add my above quality-gate step as final step you are good to go !

**Comment by NishantSingh10** [comment]
ok Thanks @PavanMudigonda.
